### ISSUE TITLE
Events stops triggering rules after random number of events get dispatched

### ISSUE THREAD

**Issue by shinrairis** [jruizgit/rules#36]
Hi,

I recently run into this problem that new events stop triggering rules after random number of events get dispatched. 

Here is my ruleset definitions:
```python
with ruleset('daware'):
    @when_all(pri(1),
              c.first << +s.last,
              c.second << (m.id == c.first.last + 1) & (m.action == 'open'))
    def daware_fopen(c):
        c.s.last = c.second.id
        logging.error('daware_fopen get message id {0}'.format(c.second.id))

    @when_all(pri(1),
              c.first << +s.last,
              c.second << (m.id == c.first.last + 1) & (m.action == 'write'))
    def daware_write_access(c):
        c.s.last = c.second.id
        logging.error('daware_write_access get message id {0}'.format(c.second.id))

    @when_all(pri(1),
              c.first << +s.last,
              c.second << (m.id == c.first.last + 1) & (m.action == 'read'))
    def daware_read_access(c):
        c.s.last = c.second.id
        logging.error('daware_read_access get message id {0}'.format(c.second.id))

    @when_all(pri(2), m.id > 0)
    def fallback(c):
        logging.error('fallback id {0}'.format(c.m.id))

    @when_start
    def start_test(host):
        host.patch_state('daware', {'sid': 1, 'last': 0})
```
Basically, I just log every event into a log file with python **logging** package. Since I want these events being logged in the same sequence as the event id, I take your advice from another post to store the last processed id in the host context. 

I have another daemon running locally which sends events by **HTTP POST** around 30k events in 30 seconds to local address http://127.0.0.1/data_aware/1.

I add a line in **Application** class to dump all the received messages to my log file, so I can confirm that all the events I post from my daemon has been received by durable_rules. 

The output log will be like this 
```
ERROR:root:daware_write_access get message id 6684
ERROR:root:daware_write_access get message id 6685
INFO:root:Get POST: {u'sid': u'1', u'action': u'write', u'id': 6882}
INFO:werkzeug:127.0.0.1 - - [29/Aug/2016 17:48:45] "POST /data_aware/1 HTTP/1.1" 200 -
```
As you can see that 6685 is the last event id that my ruleset had logged, but the werkzeug package had logged an POST with id = 6882.

This issue cannot be consistently reproduced in every around of my experiment, but I can always reproduce this in 10 rounds which means that 300k events had been sent.

This looks like a bug to me, but I cannot really confirm it. Can you think of anything that could lead to this behaviour or point me some directions to help me clarify this problem?

If you need more information or if there is anything I can help, please feel free to let me know.

**Comment by jruizgit** [comment]
Would you mind adding one more rule and run your scenario again? 

```python
        @when_all(+s.exception)
        def report_fail(c):
            print('exception {0}'.format(c.s.exception))
```

Thanks!

**Comment by shinrairis** [comment]
I add this rule to my ruleset, but it seems that no exception is raised :(
Could this have something to do with the redis? Even though I flush redis before I call run_all(), I will also add some keys with name like 'test:cid' to redis after I flush it.

**Comment by jruizgit** [comment]
I think Redis should be OK. Given the ruleset is expecting a strict increment in the id, if a single message send fails, then the ruleset will stop. Given you don't see any exceptions, most likely there are no failures in action dispatch. I'll try debugging the scenario. I will report back once I have more info.

**Comment by jruizgit** [comment]
Hi, I have pushed and published a new version with a fix for the bugs, which were blocking this scenario. There were a couple of problems:

1. When a context is saved, the engine raises an event, the mid for the event generated was colliding the the mids generated for this scenario.
2. The cleanup rule was not triggering in the redis script, so the redis memory kept increasing.

One suggestion, if in your test host you have access to your redis server you can also test your ruleset using the client (this is faster than http):

```python
from durable.lang import *

q = create_queue('daware')
i = 1
while True:
	print('Posting {0}'.format(i))
	q.post({'id': i, 'sid': 1, 'action': 'read'})
	i += 1

q.close()
```

Note: I have tested the scenario with more than 1 million events. I'm still not completely satisfied with the current scheme for generating mids for context events, as I use random numbers.

**Comment by shinrairis** [comment]
I have upgraded durable_rules via 
```
sudo pip install --upgrade durable_rules
```
I take your advice use the simple python script to generate event locally. However, the rule engine still constantly stop working in less than 100k events. I understand that there could still be mid collision, but I am wondering if this is the case since I can easily reproduce this problem everytime. Is there anyway I can print out a message or raise an exception to see if there is mid collision?

The ruleset I used is 
```python
with ruleset('data_aware'):
    @when_all(c.first << +s.last,
              c.second << (m.id == c.first.last + 1) & (m.action == 'open'))
    def daware_fopen(c):
        c.s.last = c.second.id
        print('create {0} with id {1}'.format(c.second.path, c.second.id))

    @when_all(c.first << +s.last,
              c.second << (m.id == c.first.last + 1) & (m.action == 'write'))
    def daware_write_access(c):
        c.s.last = c.second.id
        print('access {0} with id {1}'.format(c.second.path, c.second.id))

    @when_all(c.first << +s.last,
              c.second << (m.id == c.first.last + 1) & (m.action == 'read'))
    def daware_read_access(c):
        c.s.last = c.second.id
        print('read {0} with id {1}'.format(c.second.path, c.second.id))

    @when_all(+s.exception)
    def report_fail(c):
        print('Exception catched: {0}'.format(c.s.exception))
        c.s.exception = None

    @when_start
    def start_test(host):
        host.patch_state('data_aware', {'sid': 1, 'last': 0})
```

**Comment by jruizgit** [comment]
Hi, I just verified the bits published to pip are correct. I did try the complete ruleset successfully. Would you mind trying a couple of things: 

1. Try `pip uninstall durable_rules` and `pip install durable_rules`, make sure you see version 0.33.73 installed.
2. If the ruleset still doesn't work, can you please try the following scenario?

```python
  with ruleset('daware'):
    @when_all(pri(1),
              c.first << +s.last,
              c.second << (m.id == c.first.last + 1) & (m.action == 'read'))
    def daware_read_access(c):
        c.s.last = c.second.id
        logging.error('daware_read_access get message id {0}'.format(c.second.id))

    @when_all(+s.exception)
    def report_fail(c):
        print('exception {0}'.format(c.s.exception))

    @when_start
    def start_test(host):
        host.patch_state('daware', {'sid': 1, 'last': 0})
```

**Comment by shinrairis** [comment]
Hi, I followed your instructions to reinstall durable_rules and update redis-server to 3.3. However, I can still reproduce this issue constantly on both my server and workstation. Would it help debugging this by dumping some information out of redis when this happens?

Thanks

**Comment by jruizgit** [comment]
Yes, let's get some info from redis. 

1. Run the minimal ruleset I pasted above
2. Run the client until the ruleset stops dispatching (stop the client at this point), take note of the last successful mid (say it is 950)
3. Run redis-cli
4. Type `hget daware!e!1 950`
5. Type `hget daware!e!1 951`
6. Type `hget daware!e!1 952`
7. Type `hget daware!v!1 950`
8. Type `hget daware!v!1 951`
9. Type `hget daware!v!1 952`

If an event did not make it to the Redis server it won't show up in daware!v!1. If there was a collision with the event entered the entry in daware!e!1 will not show as the event which was originally raised.

**Comment by shinrairis** [comment]
Hi

The ruleset stopped dispatching event after id 16876. 
Hope this information helps.
Thanks.

```
127.0.0.1:6379> hget daware!e!1 16876
(nil)
127.0.0.1:6379> hget daware!e!1 16877
"\x83\xa2id\xcdA\xed\xa6action\xa4read\xa3sid\x01"
127.0.0.1:6379> hget daware!e!1 16878
"\x83\xa2id\xcdA\xee\xa6action\xa4read\xa3sid\x01"
127.0.0.1:6379> hget daware!v!1 16876
"1"
127.0.0.1:6379> hget daware!v!1 16877
"1"
127.0.0.1:6379> hget daware!v!1 16878
"1"
```

**Comment by jruizgit** [comment]
Thanks for providing the data. This means the even recorded successfully. One more question: if you dump the table hgetall daware!v!1, do you see any entry with an id of the form '$v-number'? I'll keep debugging the scenario on my side.

**Comment by shinrairis** [comment]
Yes, I see lots of '$v-number' entries from hgetall. Since I wrote a simple python script to dump them, please feel free to let me know if you need these entries. I have started to read the source code of durable_rules recently, hoping that I could offer more help on this project. However, I have came across the following code in rete.c
```C
static unsigned int linkAlpha(ruleset *tree,
                              unsigned int parentOffset,
                              unsigned int nextOffset) {

       // some code here ...
        result = ensureNextHashset(tree, parentAlpha);
        if (result != RULES_OK) {
            return result;
        }

        unsigned int *parentNext = &tree->nextPool[parentAlpha->value.a.nextOffset];
        unsigned int hash = nextNode->value.a.hash;
        for (entry = hash & HASH_MASK; parentNext[entry] != 0; entry = (entry + 1) % NEXT_BUCKET_LENGTH) {
            if ((entry + 1) % NEXT_BUCKET_LENGTH == (hash & HASH_MASK)) {
                return ERR_RULE_LIMIT_EXCEEDED;
            }
        }

        parentNext[entry] = nextOffset;
}
```

The HASH_MASK and NEXT_BUCKET_LENGTH is defined in rules.h
```C
#define NEXT_BUCKET_LENGTH 512
#define NEXT_LIST_LENGTH 32
#define BETA_LIST_LENGTH 16
#define HASH_MASK 0x1F
```

My question is, since the HASH_MASK makes the entry always goes between 0 to 31, why do we need to allocate a bucket length up to 512 slots in nextPool for nextOffset field?

Thanks again for your effort on this issue.

**Comment by jruizgit** [comment]
Hi, actually I meant for you to look for entries with the '$v-number' id in the daware!e!1 hashset. In theory there should only be one. If there is none, we probably have a collision. Would you mind looking into this? Also would you mind pasting in a single id entry from the daware!v!1 hashset?

Good catch, the HASH_MASK is intended to be consistent with the BUCKET_LENGTH. The BUCKET_LENGTH is the size of the trie for each alpha node. This blog entry explains how it is supposed to work:

https://jruizblog.com/2014/08/19/boosting-performance-with-c/

512 for the BUCKET_LENGTH is excessive. 128 would be much better (with the consistent HASH_MASK). Do you want to send me a pull request?

**Comment by jruizgit** [comment]
One update regarding event checkpoint collision. I have pushed and published a fix that removes random id generation altogether. I ran the example above and it worked with 1M+ events. It would be interesting to see if you still have problems. Please try version 0.33.74.

**Comment by shinrairis** [comment]
I have updated to 0.33.74 and tested this with the sample script you suggested. Now it worked with 4M+ events. So it seems that the event stopping issue does result from the event checkpoint collision. I really appreciate your great effort on this issue.

Although this issue has been resolved, I still plan to go through the whole source code to learn how durable_rules works more. I think I might need to customize it in the future to better fit my use case. 

I'll send you a pull request regarding the BUCKET_LENGTH patch I had mentioned above.
